export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/main/index',
    'pages/classInfo/index',
    'pages/evaluateInfo/index',
    'pages/personalPage/index',
    'pages/myCollection/index',
    'pages/evaluateCourseHistory/index',
    'pages/messageNotification/index',
    'pages/officialNotification/index',
    'pages/feedback/index',
    'pages/evaluate/evaluate',
    'pages/myclass/myclass',
    'pages/research/research',
    'pages/index/index',
    'pages/editPersonal/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
});
